```python
# ============================================================
# SMARTFLOW CONFIGURATION
# ============================================================

# ------------------------------------------------------------
# CAMERA CONFIGURATION
# ------------------------------------------------------------

# Replace this with your smartphone IP address when running
# SMARTFLOW locally.
CAMERA_IP = "YOUR_PHONE_IP"

CAMERA_URL = f"http://{CAMERA_IP}:8080/video"


# ------------------------------------------------------------
# YOLO / OBJECT TRACKING
# ------------------------------------------------------------

YOLO_MODEL = "yolo11n.pt"

YOLO_CONFIDENCE = 0.35

TRACKER_CONFIG = "botsort.yaml"

# Run vehicle detection approximately once every second.
DETECTION_INTERVAL = 1.0


# ------------------------------------------------------------
# DATA FILES
# ------------------------------------------------------------

# Historical dataset used for LSTM training.
BASE_FILE = "SmartFlow_Traffic_TimeSeries.csv"

# Runtime traffic data generated by the live system.
LIVE_FILE = "SmartFlow_Live_Traffic.csv"


# ------------------------------------------------------------
# LSTM MODEL
# ------------------------------------------------------------

LSTM_MODEL = "traffic_lstm.keras"

SCALER_FILE = "traffic_scaler.pkl"

# Number of historical observations used for prediction.
TIME_STEPS = 30


# ------------------------------------------------------------
# VEHICLE WEIGHTS
# ------------------------------------------------------------

# Weighted traffic-load contribution of each vehicle type.

MOTORCYCLE_WEIGHT = 0.5

CAR_WEIGHT = 1.0

BUS_WEIGHT = 3.0

TRUCK_WEIGHT = 3.5


# ------------------------------------------------------------
# TRAFFIC SIGNAL TIMING
# ------------------------------------------------------------

# Fixed yellow and red durations.

YELLOW_TIME = 5

RED_TIME = 10

# PSO green-time search boundaries.

MIN_GREEN_TIME = 10

MAX_GREEN_TIME = 60


# ------------------------------------------------------------
# PARTICLE SWARM OPTIMIZATION (PSO)
# ------------------------------------------------------------

PSO_PARTICLES = 20

PSO_ITERATIONS = 30

PSO_INERTIA = 0.7

PSO_COGNITIVE = 1.5

PSO_SOCIAL = 1.5


# ------------------------------------------------------------
# PSO OBJECTIVE FUNCTION
# ------------------------------------------------------------

# Relative weights used in the signal optimization cost function.

WAITING_COST_WEIGHT = 1.0

QUEUE_COST_WEIGHT = 1.0

UNDER_SERVICE_PENALTY = 2.0

EXCESSIVE_GREEN_PENALTY = 1.0


# ------------------------------------------------------------
# TRAFFIC SERVICE MODEL
# ------------------------------------------------------------

# Estimated traffic-load service rate per second of green time.

SERVICE_RATE = 0.5
```
